version: '3.8'

services:
    # -----------------------
    # PostgreSQL
    # -----------------------
    postgres:
        image: postgres:15
        container_name: aftercode-db-postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db-postgres-data:/var/lib/postgresql/data

    # -----------------------
    # ZooKeeper (necessário para o Kafka)
    # -----------------------
    zookeeper:
        image: bitnami/zookeeper:latest
        container_name: aftercode-zookeeper
        environment:
            - ALLOW_ANONYMOUS_LOGIN=${ZOOKEEPER_ALLOW_ANONYMOUS_LOGIN}
        ports:
            - '2181:2181'
        restart: always

    # -----------------------
    # Kafka
    # -----------------------
    kafka:
        image: bitnami/kafka:latest
        container_name: aftercode-kafka
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
        environment:
            - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
            - KAFKA_CFG_ZOOKEEPER_CONNECT=${KAFKA_CFG_ZOOKEEPER_CONNECT}
            - KAFKA_CFG_ADVERTISED_LISTENERS=${KAFKA_CFG_ADVERTISED_LISTENERS}
            - ALLOW_PLAINTEXT_LISTENER=${ALLOW_PLAINTEXT_LISTENER}
        restart: always

    # -----------------------
    # Redis
    # -----------------------
    redis:
        image: redis:7
        container_name: aftercode-redis
        restart: always
        ports:
            - '6379:6379'

volumes:
    db-postgres-data:
        external: false
