version: '3.8'

services:
    # -----------------------
    # PostgreSQL
    # -----------------------
    postgres:
        image: postgres:15
        container_name: db-postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: database
        volumes:
            - db-postgres-data:/var/lib/postgresql/data

    # -----------------------
    # ZooKeeper (necessário para o Kafka)
    # -----------------------
    zookeeper:
        image: bitnami/zookeeper:latest
        container_name: zookeeper
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        ports:
            - '2181:2181'
        restart: always

    # -----------------------
    # Kafka
    # -----------------------
    kafka:
        image: bitnami/kafka:latest
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            # Para acessar de fora, usamos ADVERTISED_LISTENERS apontando para "localhost"
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
            # Se quiser acessar de outro host/container, pode ajustar para "kafka:9092" ou o IP da máquina
            - ALLOW_PLAINTEXT_LISTENER=yes
        restart: always

    # -----------------------
    # Redis
    # -----------------------
    redis:
        image: redis:7
        container_name: redis
        restart: always
        ports:
            - '6379:6379'

# Cria um volume para armazenar dados do Postgres
volumes:
    db-postgres-data:
        external: false
