version: '3.8'

services:
    # -----------------------
    # PostgreSQL
    # -----------------------
    postgres:
        image: postgres:15
        container_name: aftercode-db-postgres
        restart: always
        ports:
            - '${DATABASE_PORT}:5432'
        environment:
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_NAME: ${DATABASE_NAME}
        volumes:
            - db-postgres-data:/var/lib/postgresql/data

    # -----------------------
    # ZooKeeper (necessário para o Kafka)
    # -----------------------
    zookeeper:
        image: bitnami/zookeeper:latest
        container_name: aftercode-zookeeper
        environment:
            - ALLOW_ANONYMOUS_LOGIN=${ZOOKEEPER_ALLOW_ANONYMOUS_LOGIN}
        ports:
            - '2181:2181'
        restart: always

    # -----------------------
    # Kafka
    # -----------------------
    kafka:
        image: bitnami/kafka:latest
        container_name: aftercode-kafka
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
        environment:
            - KAFKA_CFG_NODE_ID=1
            - KAFKA_CFG_PROCESS_ROLES=broker
            - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
            - KAFKA_CFG_ZOOKEEPER_CONNECT=${KAFKA_CFG_ZOOKEEPER_CONNECT}
            - KAFKA_CFG_ADVERTISED_LISTENERS=${KAFKA_CFG_ADVERTISED_LISTENERS}
            - ALLOW_PLAINTEXT_LISTENER=${ALLOW_PLAINTEXT_LISTENER}
        restart: always

    # -----------------------
    # Redis
    # -----------------------
    redis:
        image: redis:7
        container_name: aftercode-redis
        restart: always
        ports:
            - '${REDIS_PORT}:6379'

volumes:
    db-postgres-data:
        external: false
